/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puzzlegamewithownpicture;

import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author sean
 */
public class GameSetting extends javax.swing.JFrame {

    /**
     * Creates new form GameSetting
     */
    
    //path for exist pictures
    String inputImagePath = "/resources/images/tomandjerry.jpg";
    String inputImagePath1 = "/resources/images/tomandjerry.jpg";
    String inputImagePath2 = "/resources/images/mario.jpg";
    String inputImagePath3 = "/resources/images/pokemon.png";
    String inputImagePath4 = "/resources/images/plus.jpg";
    
    //initial value
    private int rows = 4;
    private int cols = 4;
    private int userChoice = 0;
    
    public GameSetting() {
        initComponents();
        
        //initialize: choose first image and easy level
        //show pictures on the button
        jButton1.setFont(new java.awt.Font("Apple LiGothic", 0, 36));
        jButton6.setIcon(new ImageIcon(resizedImage(inputImagePath1, 120, userChoice)));
        jButton7.setIcon(new ImageIcon(resizedImage(inputImagePath2, 90, userChoice)));
        jButton8.setIcon(new ImageIcon(resizedImage(inputImagePath3, 90, userChoice)));
        jButton9.setIcon(new ImageIcon(resizedImage(inputImagePath4, 90, userChoice)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(655, 455));
        setMinimumSize(new java.awt.Dimension(655, 455));
        setPreferredSize(new java.awt.Dimension(655, 455));

        jLabel1.setFont(new java.awt.Font("Apple LiGothic", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Level");

        jButton1.setFont(new java.awt.Font("Apple LiGothic", 0, 18)); // NOI18N
        jButton1.setText("Easy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Apple LiGothic", 0, 18)); // NOI18N
        jButton2.setText("Normal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Apple LiGothic", 0, 18)); // NOI18N
        jButton3.setText("Difficult");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Apple LiGothic", 0, 18)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Apple LiGothic", 0, 18)); // NOI18N
        jButton5.setText("Start");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Apple LiGothic", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Game Setting");

        jButton6.setMaximumSize(new java.awt.Dimension(120, 120));
        jButton6.setMinimumSize(new java.awt.Dimension(120, 120));
        jButton6.setPreferredSize(new java.awt.Dimension(120, 120));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setMaximumSize(new java.awt.Dimension(120, 120));
        jButton7.setMinimumSize(new java.awt.Dimension(120, 120));
        jButton7.setPreferredSize(new java.awt.Dimension(120, 120));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setMaximumSize(new java.awt.Dimension(120, 120));
        jButton8.setMinimumSize(new java.awt.Dimension(120, 120));
        jButton8.setPreferredSize(new java.awt.Dimension(120, 120));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setMaximumSize(new java.awt.Dimension(120, 120));
        jButton9.setMinimumSize(new java.awt.Dimension(120, 120));
        jButton9.setPreferredSize(new java.awt.Dimension(120, 120));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButton4)
                        .addGap(6, 6, 6)
                        .addComponent(jButton5))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //back to main menu frame
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MainMenu mm = new MainMenu();
        this.setVisible(false);
        mm.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    //go to play frame
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Play p = new Play();
        p.readInformation(inputImagePath, rows, cols, userChoice);
        this.setVisible(false);
        p.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    //choose easy level - 4*4
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //TODO add your handling code here:
        rows = 4;
        cols = 4;
        
        //highlight the chosen level
        jButton1.setFont(new java.awt.Font("Apple LiGothic", 0, 36));
        jButton2.setFont(new java.awt.Font("Apple LiGothic", 0, 18));
        jButton3.setFont(new java.awt.Font("Apple LiGothic", 0, 18));
    }//GEN-LAST:event_jButton1ActionPerformed

    //choose normal level - 6*6
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        rows = 6;
        cols = 6;
        
        //highlight the chosen level
        jButton1.setFont(new java.awt.Font("Apple LiGothic", 0, 18));
        jButton2.setFont(new java.awt.Font("Apple LiGothic", 0, 36));
        jButton3.setFont(new java.awt.Font("Apple LiGothic", 0, 18));
    }//GEN-LAST:event_jButton2ActionPerformed

    //choose easy level - 8*8
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        rows = 8;
        cols = 8;
        
        //highlight the chosen level
        jButton1.setFont(new java.awt.Font("Apple LiGothic", 0, 18));
        jButton2.setFont(new java.awt.Font("Apple LiGothic", 0, 18));
        jButton3.setFont(new java.awt.Font("Apple LiGothic", 0, 36));
    }//GEN-LAST:event_jButton3ActionPerformed

    //choose the first image
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        inputImagePath = inputImagePath1;
        inputImagePath4 = "/resources/images/plus.jpg";
        userChoice = 0;
        
        //highlight the chosen image
        jButton6.setIcon(new ImageIcon(resizedImage(inputImagePath1, 120, userChoice)));
        jButton7.setIcon(new ImageIcon(resizedImage(inputImagePath2, 90, userChoice)));
        jButton8.setIcon(new ImageIcon(resizedImage(inputImagePath3, 90, userChoice)));
        jButton9.setIcon(new ImageIcon(resizedImage(inputImagePath4, 90, userChoice)));
    }//GEN-LAST:event_jButton6ActionPerformed

    //choose the second image
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        inputImagePath = inputImagePath2;
        inputImagePath4 = "/resources/images/plus.jpg";
        userChoice = 0;
        
        //highlight the chosen image
        jButton6.setIcon(new ImageIcon(resizedImage(inputImagePath1, 90, userChoice)));
        jButton7.setIcon(new ImageIcon(resizedImage(inputImagePath2, 120, userChoice)));
        jButton8.setIcon(new ImageIcon(resizedImage(inputImagePath3, 90, userChoice)));
        jButton9.setIcon(new ImageIcon(resizedImage(inputImagePath4, 90, userChoice)));
    }//GEN-LAST:event_jButton7ActionPerformed

    //choose the third image
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        inputImagePath = inputImagePath3;
        inputImagePath4 = "/resources/images/plus.jpg";
        userChoice = 0;
        
        //highlight the chosen image
        jButton6.setIcon(new ImageIcon(resizedImage(inputImagePath1, 90, userChoice)));
        jButton7.setIcon(new ImageIcon(resizedImage(inputImagePath2, 90, userChoice)));
        jButton8.setIcon(new ImageIcon(resizedImage(inputImagePath3, 120, userChoice)));
        jButton9.setIcon(new ImageIcon(resizedImage(inputImagePath4, 90, userChoice)));
    }//GEN-LAST:event_jButton8ActionPerformed

    //let users to choose their own picture
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        jfc.showDialog(null,"Select picture");
        jfc.setVisible(true);
        File file = jfc.getSelectedFile();
        String path = file.getAbsolutePath();
        inputImagePath4 = path;
        inputImagePath = inputImagePath4;
        userChoice = 1;
        
        //highlight the chosen image
        jButton6.setIcon(new ImageIcon(resizedImage(inputImagePath1, 90, 0)));
        jButton7.setIcon(new ImageIcon(resizedImage(inputImagePath2, 90, 0)));
        jButton8.setIcon(new ImageIcon(resizedImage(inputImagePath3, 90, 0)));
        jButton9.setIcon(new ImageIcon(resizedImage(inputImagePath4, 120, userChoice)));
    }//GEN-LAST:event_jButton9ActionPerformed

    // reads input image
    private BufferedImage resizedImage(String inputImagePath, int size, int userChoice) {
        BufferedImage inputImage = null;
        
        //user choose use absolute path
        if (userChoice == 0) {
            try {
                inputImage = ImageIO.read(PuzzleGame.class.getResource(inputImagePath));
            } catch (IOException ex) {
                Logger.getLogger(PuzzleGame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //initial choose use related path
        else {
            try {
                inputImage = ImageIO.read(new File(inputImagePath));
            } catch (IOException ex) {
                Logger.getLogger(GameSetting.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        // creates output image
        BufferedImage outputImage = new BufferedImage(size, size, inputImage.getType());
 
        // scales the input image to the output image
        Graphics2D g2d = outputImage.createGraphics();
        g2d.drawImage(inputImage, 0, 0, size, size, null);
        g2d.dispose();
        
        return outputImage;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
